### ISSUE TITLE
Missing 'MistralType' in scope of the app

### ISSUE THREAD

**Issue by bhushangawde** [cardona/SwiftMistralCoreML-DemoApp#9]
Hello, 

Thank you for the app.
I tried to run this app in my local.

But the 'MistralType' datatype is missing from the SwiftMistralCoreML Package that is added as a dependency in this app.

In the package, there is a missing ModelType parameter for Mistral.

Kindly let me know the solution.

Thanks

**Comment by bhushangawde** [comment]
I just checked that the demo app adds the 1.1.0 version of the SwiftMistralCoreML package by default as a dependency which points to the initial commit of SwiftMistralCoreML. 

How should I get the latest one?

Just right-clicking on package dependency and selecting "Update package" in XCode does not help.

**Comment by cardona** [comment]
Hello,

Apologies for the delay in responding. It seems you are currently using version 1.1.0 of the SwiftMistralCoreML package, while the latest available version is 1.2.0.

To update the package in Xcode, please follow these steps:

Go to the menu File -> Packages -> Update to Latest Package Versions.
This will automatically update all dependencies to their latest compatible versions, including SwiftMistralCoreML.
Once updated, the app should build successfully using the latest version of the package.

If you encounter any further issues, feel free to reach out.

Thanks

**Comment by bhushangawde** [comment]
Hi  @cardona 

I was able to solve this issue on the same day. Sorry to keep it open. :D

Btw, I would like to know if you are planning to support for iOS.
Opening another issue to discuss it.
